version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mentor
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ../:/app
    env_file:
      - ../.env
    command: bash -lc "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports: ["8000:8000"]
    depends_on: [db, redis]

volumes:
  pgdata:
